language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - postgresql

deploy:
  provider: script

before_script:
  - psql -c 'create database politico;' -U postgres

script:
  - npm test

after_success:
  - npm run coverage
  
   