language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - postgresql

deploy:
  provider: script

before_script:
  - psql -c 'create database politico_test;' -U postgres

script:
  - npm start

after_success:
  - npm  test
  - npm run coverage 
  
   
